#!/bin/bash

echo
echo Please choose one of the options below:
echo 'a = Display Date and Time'
echo 'b = List files and directories'
echo
	read choices
	case $choices in
a) date;;
b) ls;;
*) echo invalid choise - bye.
	esac 
